stages:
  - name: test
  - name: buildDocker
    if: branch == master
  - name: deploy
    if: branch == production
cache:
  directories:
  # We cache the SDK so we don't have to download it again on subsequent builds.
  - $HOME/google-cloud-sdk
  - $HOME/.cache/pip

services:
  - docker
  - postgresql

addons:
  postgresql: "10"

env:
  global:
  # Do not prompt for user input when using any SDK methods.
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1

jobs:
  include:
    - stage: test
      dist: bionic
      python: "3.7.6"
      env:
        - PIP_CACHE_DIR="$HOME/.cache/pip"
        - FLASK_CONFIG_MODE=testing_ci
        - PYENV_VERSION=3.7.6
      install: "pip3 install -r requirements.txt"
      before_script:
        - psql -c 'create database composedb_test;' -U postgres
      script: pytest
    - stage: buildDocker
      script: 'if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then ./build_docker.sh ; fi'
